[config]
default_to_workspace = false
additional_profiles = ["debug"]

[env]
TARGET_DIR = "target"

[tasks.choose_profile.env]
RUSTFLAGS = "-Copt-level=s"
MODE = "release"
ADDITIONAL = "--release"

    [tasks.choose_profile.env.debug]
    RUSTFLAGS = ""
    MODE = "debug"
    ADDITIONAL = "--profile=dev"

[tasks.run-server]
command = "cargo"
toolchain = "stable"
args = ["run", "-p", "datawave-server", "${ADDITIONAL}"]
dependencies = ["choose_profile"]

[tasks.run]
run_task = [
    { name = ["run-server"] },
]


[tasks.fmt-check]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--check"]

[tasks.clippy]
toolchain = "stable"
command = "cargo"
args = ["clippy", "--all-targets", "--", "-D", "warnings"]

[tasks.lint-test]
toolchain = "stable"
command = "cargo"
args = ["test"]
dependencies = ["fmt-check", "clippy"]
